defaults:
  - data_loading: normal_dataset
  - model: model
  - freeze_layers: freeze_layers
  - fine_tuning: fine_tuning
  - logging: logging
  - inference: inference
  - onnx_converter: onnx_converter
