defaults:
  - data_loading: data_loading
  - model: model
  - freeze_layers: freeze_layers
  - fine_tuning: fine-tuning
  - logging: logging
  - inference: inference
  - validation: validation
  - onnx_converter: onnx-converter
